### ISSUE TITLE
HACS compliant

### ISSUE THREAD

**Issue by rsmk45** [zxdavb/evohome-async#7]
Please make this HACS compliant, like 'evohome_cc'. 
The integration cannot be added to HA as a HACS Custom repository:
"Repository structure for master is not compliant"

**Comment by zxdavb** [comment]
@rsmk45 This is _not_ a HA custom component. It is a client library, as used by the official **evohome** integration. Please see: https://www.home-assistant.io/integrations/evohome/

As you say, there _is_ a HACS integration, called **evohome_cc**, which uses RF (with a USB dongle) instead of the vendor's web API, see: 
 - https://github.com/zxdavb/evohome_cc
 - https://community.home-assistant.io/t/honeywell-ch-dhw-via-rf-evohome-sundial-hometronics-chronotherm
